-- Generado desde data/dinners.json con: npm run db:seed:generate
-- Es idempotente para poder aplicarlo más de una vez sin duplicar datos.
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO dinners (id, title, date) VALUES ('fideos-caseros', 'Fideos caseros', '2026-06-19');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('fideos-caseros', 'Jo');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('fideos-caseros', 'Lu');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('fideos-caseros', 'Valen');
INSERT OR IGNORE INTO dishes (id, dinner_id, name, description) VALUES ('empanadas-osobuco', 'fideos-caseros', 'Empanadas de osobuco', NULL);
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-empanadas-osobuco-1', 'fideos-caseros', 'dish', 'empanadas-osobuco', 'Lu', 9.7, 'Se deshacían solas');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-empanadas-osobuco-2', 'fideos-caseros', 'dish', 'empanadas-osobuco', 'Valen', 9.5, 'El relleno era increíble');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-empanadas-osobuco-3', 'fideos-caseros', 'dish', 'empanadas-osobuco', 'Jo', 9.2, 'Bien jugosas');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-empanadas-osobuco-4', 'fideos-caseros', 'dish', 'empanadas-osobuco', 'Juan', 9.2, 'Salieron mejor de lo esperado');
INSERT OR IGNORE INTO dishes (id, dinner_id, name, description) VALUES ('fideos-hongos', 'fideos-caseros', 'Fideos con salsa de hongos', NULL);
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-fideos-hongos-1', 'fideos-caseros', 'dish', 'fideos-hongos', 'Lu', 9.5, 'La salsa estaba increíble');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-fideos-hongos-2', 'fideos-caseros', 'dish', 'fideos-hongos', 'Valen', 9, 'Quiero repetir');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-fideos-hongos-3', 'fideos-caseros', 'dish', 'fideos-hongos', 'Jo', 9, 'La pasta quedó en su punto');
INSERT OR IGNORE INTO dishes (id, dinner_id, name, description) VALUES ('helado-dulce-de-leche', 'fideos-caseros', 'Helado de dulce de leche', NULL);
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-helado-dulce-de-leche-1', 'fideos-caseros', 'dish', 'helado-dulce-de-leche', 'Lu', 9, 'Cremoso y nada empalagoso');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-helado-dulce-de-leche-2', 'fideos-caseros', 'dish', 'helado-dulce-de-leche', 'Valen', 9, 'El cierre perfecto');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-dish-helado-dulce-de-leche-3', 'fideos-caseros', 'dish', 'helado-dulce-de-leche', 'Jo', 9, 'Quiero otro kilo');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('trumpeter-malbec', 'fideos-caseros', 'Trumpeter', 'Tintos', 'Rutini Wines', 'Malbec');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-trumpeter-malbec-1', 'fideos-caseros', 'wine', 'trumpeter-malbec', 'Lu', 8.7, 'Muy amable');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-trumpeter-malbec-2', 'fideos-caseros', 'wine', 'trumpeter-malbec', 'Valen', 8.8, 'Frutado');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-trumpeter-malbec-3', 'fideos-caseros', 'wine', 'trumpeter-malbec', 'Jo', 8.6, 'Acompañó bien');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('patrillos-malbec', 'fideos-caseros', 'Patrillos', 'Tintos', 'Patrillos', 'Malbec');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-patrillos-malbec-1', 'fideos-caseros', 'wine', 'patrillos-malbec', 'Lu', 8.5, 'Frutado y suave');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-patrillos-malbec-2', 'fideos-caseros', 'wine', 'patrillos-malbec', 'Valen', 9, 'Fue perfecto con la salsa');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-patrillos-malbec-3', 'fideos-caseros', 'wine', 'patrillos-malbec', 'Jo', 8.5, 'Lo volvería a comprar');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-patrillos-malbec-4', 'fideos-caseros', 'wine', 'patrillos-malbec', 'Juan', 9.6, 'El que mejor acompañó la cena');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('dv-catena-malbec', 'fideos-caseros', 'DV Catena', 'Tintos', 'Catena Zapata', 'Malbec');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-dv-catena-malbec-1', 'fideos-caseros', 'wine', 'dv-catena-malbec', 'Lu', 9.2, 'Profundo');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-dv-catena-malbec-2', 'fideos-caseros', 'wine', 'dv-catena-malbec', 'Valen', 9.1, 'El favorito de la noche');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-dv-catena-malbec-3', 'fideos-caseros', 'wine', 'dv-catena-malbec', 'Jo', 9, 'Muy equilibrado');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('saurus-pinot-noir', 'fideos-caseros', 'Saurus', 'Tintos', 'Familia Schroeder', 'Pinot Noir');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-saurus-pinot-noir-1', 'fideos-caseros', 'wine', 'saurus-pinot-noir', 'Lu', 8.5, 'Liviano');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-saurus-pinot-noir-2', 'fideos-caseros', 'wine', 'saurus-pinot-noir', 'Jo', 8.3, 'Fresco');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('costa-pampa-sauvignon-blanc', 'fideos-caseros', 'Costa & Pampa', 'Blancos', 'Trapiche Costa & Pampa', 'Sauvignon Blanc');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-costa-pampa-sauvignon-blanc-1', 'fideos-caseros', 'wine', 'costa-pampa-sauvignon-blanc', 'Lu', 8.9, 'Bien ácido');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-costa-pampa-sauvignon-blanc-2', 'fideos-caseros', 'wine', 'costa-pampa-sauvignon-blanc', 'Valen', 8.8, 'Muy fresco');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-fideos-caseros-wine-costa-pampa-sauvignon-blanc-3', 'fideos-caseros', 'wine', 'costa-pampa-sauvignon-blanc', 'Jo', 8.7, 'Gran blanco');
INSERT OR IGNORE INTO dinners (id, title, date) VALUES ('pizza', 'Pizza', '2026-08-13');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('pizza', 'Pepe');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('pizza', 'Agus');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('pizza', 'Lucio');
INSERT OR IGNORE INTO dinner_guests (dinner_id, name) VALUES ('pizza', 'Mamá');
INSERT OR IGNORE INTO dishes (id, dinner_id, name, description) VALUES ('pizza-muzza', 'pizza', 'Pizza de muzzarella', NULL);
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-pizza-dish-pizza-muzza-1', 'pizza', 'dish', 'pizza-muzza', 'Agus', 9, 'Piso crocante, como debe ser');
INSERT OR IGNORE INTO dishes (id, dinner_id, name, description) VALUES ('pizza-fugazza', 'pizza', 'Fugazzeta', NULL);
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-pizza-dish-pizza-fugazza-1', 'pizza', 'dish', 'pizza-fugazza', 'Mamá', 8, 'Muy rica');
INSERT OR IGNORE INTO wines (id, dinner_id, name, category, winery, varietal) VALUES ('domingo-molina', 'pizza', 'Domingo Molina', 'Otros', 'Domingo Molina', 'Tannat');
INSERT OR IGNORE INTO reviews (id, dinner_id, item_type, item_id, author, score, comment) VALUES ('seed-pizza-wine-domingo-molina-1', 'pizza', 'wine', 'domingo-molina', 'Pepe', 8, 'Con mucho cuerpo');
